# Generated by Django 3.2 on 2021-04-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
