# Generated by Django 3.2 on 2021-04-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_commentpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
